version: '3.8'

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: ваше_имя_пользователя
      POSTGRES_PASSWORD: ваш_пароль
      POSTGRES_DB: ваша_база_данных

  backend:
    image: ваш_логин/образ_бэкенда:тег
    depends_on:
      - postgres
    environment:
      - DATABASE_URL=postgresql://ваше_имя_пользователя:ваш_пароль@postgres:5432/ваша_база_данных

  frontend:
    image: ваш_логин/образ_фронтенда:тег
    depends_on:
      - backend
    ports:
      - "80:3000"
