name: Build and Deploy

on:
  push:
    branches:
      - master

jobs:
  client_build:
        runs-on: ubuntu-latest
        defaults:
            run:
                working-directory: frontend
        steps:
            - uses: actions/checkout@master
            - name: login to docker
              run: |
                docker login -u ${{secrets.DOCKER_LOGIN}} -p ${{secrets.DOCKER_PASSWORD}}
            - name: build image
              run: docker build -t ${{secrets.DOCKER_LOGIN}}/${{secrets.DOCKER_CLIENT_NAME}}:deploy -f Dockerfile .
            - name: push build
              run: docker push ${{secrets.DOCKER_LOGIN}}/${{secrets.DOCKER_CLIENT_NAME}}:deploy


  server_build:
        runs-on: ubuntu-latest
        defaults:
            run:
                working-directory: backend
        steps:
            - uses: actions/checkout@master
            - name: login to docker
              run: | 
                docker login -u ${{secrets.DOCKER_LOGIN}} -p ${{secrets.DOCKER_PASSWORD}}
            - name: build image
              run: docker build -t ${{secrets.DOCKER_LOGIN}}/${{secrets.DOCKER_SERVER_NAME}}:deploy -f Dockerfile .
            - name: push build
              run: docker push ${{secrets.DOCKER_LOGIN}}/${{secrets.DOCKER_SERVER_NAME}}:deploy
  deploy:
         runs-on: ubuntu-latest
         needs: [client_build, server_build]
         steps:
            - name: ssh connection
              uses: appleboy/ssh-action@v1.0.3
              with:
                host: ${{secrets.SSH_HOST}}
                username: ${{secrets.SSH_USERNAME}}
                password: ${{secrets.SSH_PASSWORD}}
                script: bash alko-deploy.sh
        