name: Build and Deploy

on:
  push:
    branches:
      - master

jobs:
  client_build:
        runs-on: ubuntu-latest
        defaults:
            run:
                working-directory: frontend
        steps:
            - uses: actions/checkout@master
            - name: login to docker
              run: |
                docker login -u ${{secrets.DOCKER_LOGIN}} -p ${{secrets.DOCKER_PASSWORD}}
            - name: build image
              run: docker build -t ${{secrets.DOCKER_LOGIN}}/${{secrets.DOCKER_CLIENT_NAME}}:deploy -f Dockerfile .
            - name: push build
              run: docker push ${{secrets.DOCKER_LOGIN}}/${{secrets.DOCKER_CLIENT_NAME}}:deploy


    server_build:
        runs-on: ubuntu-latest
        defaults:
            run:
                working-directory: backend
        steps:
            - uses: actions/checkout@master
            - name: login to docker
              run: | 
                docker login -u ${{secrets.DOCKER_LOGIN} -p ${{secrets.DOCKER_PASSWORD}}
            - name: build image
              run: docker build -t ${{secrets.DOCKER_LOGIN}}/${{secrets.DOCKER_SERVER_NAME}}:deploy -f Dockerfile .
            - name: push build
              run: docker push ${{secrets.DOCKER_LOGIN}}/${{secrets.DOCKER_SERVER_NAME}}:deploy